Create component and export it `<Link >`
selsa-inube/inubekit-link pull request #1
Opened 2024-03-18 21:27 UTC by JanuarAsprilla

The  `<Link >` component** has been created at the same time it is exported for use

2024-03-19 16:42 UTC, cmarin001 requested changes

2024-03-19 16:42 UTC, cmarin001 commented on src/Link/Link.stories.tsx
> +export const Default = (args: ILink) => {
Please revise the export statement to match the convention used in other components, ensuring it is positioned at the end of the file

2024-03-19 16:42 UTC, cmarin001 commented on src/Link/index.tsx
> +export interface ILink {
Please revise the export statement to match the convention used in other components, ensuring it is positioned at the end of the file

2024-03-19 16:51 UTC, JanuarAsprilla commented on src/Link/index.tsx
> +export interface ILink {
solved

2024-03-19 21:50 UTC, wfercanas requested changes

2024-03-19 21:50 UTC, wfercanas commented on src/Link/Link.stories.tsx
> +  tittle: "data/Link",
It's `title`

2024-03-19 21:50 UTC, wfercanas commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
Check  `Text` component. There we have a `type` prop that indicates if the text is a label, a body or any other type of text.
Here we can assume that the default type is "body"

2024-03-19 21:50 UTC, wfercanas commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
Size is not something that the end user decides. That is a result value of the `type` selected. Adjust styles.js so that the `font-size` uses typography tokens.

2024-03-19 21:50 UTC, wfercanas commented on src/Link/index.tsx
> +  path?: string;
This prop cannot be optional because the link won't work as intended.

2024-03-19 21:50 UTC, wfercanas commented on src/Link/props.ts
Add here the `type` prop, define its type with typescript and export it.

2024-03-19 21:50 UTC, wfercanas commented on src/Link/styles.js
> +      theme?.typography?.label?.large?.font || "Roboto"},
Don't assume that it will always be a `label`. Use the `type` prop.

2024-03-19 21:50 UTC, wfercanas commented on src/Link/styles.js
> +  font-size: ${({ $size }) => $size};
Extract the value from tokens and delete this `size` prop

2024-03-19 21:50 UTC, wfercanas commented on vite.config.ts
> +        "@inubekit/foundations",
You're missing "react-router-dom"

2024-03-19 22:46 UTC, JanuarAsprilla commented on src/Link/Link.stories.tsx
> +  tittle: "data/Link",
solved

2024-03-19 22:50 UTC, JanuarAsprilla commented on vite.config.ts
> +        "@inubekit/foundations",
solved

2024-03-19 22:59 UTC, JanuarAsprilla commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
solved

2024-03-19 23:01 UTC, JanuarAsprilla commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
solved

2024-03-19 23:02 UTC, JanuarAsprilla commented on src/Link/styles.js
> +      theme?.typography?.label?.large?.font || "Roboto"},
solved

2024-03-19 23:02 UTC, JanuarAsprilla commented on src/Link/styles.js
> +  font-size: ${({ $size }) => $size};
solved

2024-03-27 17:07 UTC, wfercanas commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
If the default type is `body` is because the prop type is optional, otherwise it wouldn't make sense to define a default if `ILink` always demands to pass the prop value.

2024-03-27 20:34 UTC, JanuarAsprilla commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
solved

2024-03-27 20:38 UTC, JanuarAsprilla commented on src/Link/styles.js
> +      theme?.typography?.label?.large?.font || "Roboto"},
solved

2024-04-01 15:38 UTC, wfercanas commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
The `type` and `size` props should be optional and have default values.

2024-04-01 15:41 UTC, wfercanas commented on src/Link/styles.js
> +      theme?.typography?.label?.large?.font || "Roboto"},
Use the same definition as in `<Text />` for font-family:
![image](https://github.com/selsa-inube/inubekit-link/assets/36939686/01720817-e771-45a1-a003-1215696326a1)

2024-04-01 18:12 UTC, JanuarAsprilla commented on src/Link/styles.js
> +      theme?.typography?.label?.large?.font || "Roboto"},
solved

2024-04-01 18:15 UTC, JanuarAsprilla commented on src/Link/index.tsx
> +  const { children, size = "20px", path } = props;
solved

2024-04-02 14:41 UTC, wfercanas requested changes

2024-04-02 21:21 UTC, wfercanas commented on src/Link/index.tsx
> +  const { children, size = "small", type = "label", path } = props;
El type sí quedó en "body" pero el size sigue en "small"

2024-04-02 21:59 UTC, JanuarAsprilla commented on src/Link/index.tsx
> +  const { children, size = "small", type = "label", path } = props;
sorry for confusions, corrections finalized

2024-04-02 22:55 UTC, wfercanas approved these changes

2024-04-02 22:55 UTC, merged